---
- name: Installing jenkins on slave1
  hosts: k8s-slave1 
  become: true
  tasks: 
    - name: installing apache2 on slave1
      apt: name=apache2 state=latest

- name: Installing java on slave2
  hosts: k8s-slave2 
  become: true
  tasks: 
    - name: installing nginx on slave2
      apt: name=nginx state=latest
